### ISSUE TITLE
Use DockerHub automated build to provide official docker image

### ISSUE THREAD

**Issue by tobegit3hub** [saiprashanths/dl-docker#2]
Now we can build the new docker image from Dockerfile in this repo. Is that possible to provide the official one so that we don't need to build by ourselves and just `docker pull saiprashanths/dl-docker`?

**Comment by saiprashanths** [comment]
The CPU build is on Docker Hub (via automated build) and you can get that using `docker pull floydhub/dl-docker:cpu`. 

The automated build for the GPU on Docker Hub is timing out, likely because they have timeout restrictions. I can build locally and push it, but that makes it difficult to keep it up to date with changes in the Dockerfile.gpu. I'll see if I can work around the timeout. Keeping this issue open for now.

**Comment by jarrydfillmore** [comment]
Agree!

**Comment by tobegit3hub** [comment]
Good job @saiprashanths 👍 

It would be great to add the usage of `docker pull floydhub/dl-docker:cpu` in README.

**Comment by saiprashanths** [comment]
I've added docker pull for the cpu version to the README. I'll look into splitting the GPU file into multiple Dockerfiles to see if that helps overcome the timeout issue.

**Comment by Kaixhin** [comment]
CUDA builds do indeed tend to trigger timeouts (since the hardware specs are rather minimal too) - I've needed to split builds for [Caffe](https://hub.docker.com/r/kaixhin/cuda-caffe-deps/) and [Torch](https://hub.docker.com/r/kaixhin/cuda-torch-deps/) for example.

A (messy) alternative is to have either `kaixhin/cuda-caffe` or `kaixhin/cuda-torch` as your base image. Even then you may still need to split the build though...

**Comment by saiprashanths** [comment]
I'm working on splitting the build. First try timed out again. Will try another variation or use your image.

**Comment by Kaixhin** [comment]
If you want to squeeze more instructions into your builds, send outputs to `/dev/null`. I talked to someone at Docker who said that logging actually has a reasonable impact, so this is a valid strategy (although it makes debugging impossible).
