### ISSUE TITLE
Unable to use GPU with Theano

### ISSUE THREAD

**Issue by Mikeprod** [saiprashanths/dl-docker#8]
I built your docker for gpu with the provided info in the README. Then when I use the command to launch the docker, it runs fine.
In a new notebook, I simply type `import theano` and I get the following error :
```
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1
```
What am I doing wrong ?

I then tested the cpu version, theano and Keras are working just fine.

**Comment by saiprashanths** [comment]
You probably have something else running on your GPU, which is causing Theano to not be able to allocate enough memory. You shouldn't get this error if you kill all processes using GPU. Alternatively, you can edit `/root/.theanorc` to remove the line `cnmem=0.95` (or change it to a lower fraction)

The cnmem parameter provides a parameter that dictates the fraction of the total GPU memory to be reserved for the CUDA memory allocator. See [http://deeplearning.net/software/theano/library/config.html#config.config.lib.cnmem](http://deeplearning.net/software/theano/library/config.html#config.config.lib.cnmem) for more details.

**Comment by Mikeprod** [comment]
OK, I just deleted the part [lib] in the theano config file to make it work. Thanks for the really quick answer.

**Comment by saiprashanths** [comment]
@mahdaneh I'm not too sure about this, but this is my speculation: `nvidia-docker` does some GPU isolation (see [https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation](https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation)). Hence, it might not be possible for 2 containers to access the same GPU. You can try running multiple Theano processes from inside the same container to see if it works.

**Comment by mahdaneh** [comment]
Thanks for your suggestion. I found why I get this error since the GPU has not enough memory to run several Theano processes concurrently!  Checking nvidia-smi is good to assess whether the GPU has enough memory to run another Theano process or not. Another important thing is that the users should set the cnmem to a small number if they wish to run concurrently several processes on GPU, otherwise, one Theano or Tensorflow process can take all GPU memory by default and does not let other processes start their run.
